from enum import StrEnum


class AvatarBackgroundColor(StrEnum):
    STEEL_BLUE = "#6B8EAD"
    SAGE_GREEN = "#7A9E7E"
    WARM_TAUPE = "#B08968"
    DUSTY_PURPLE = "#8D6A9F"
    TEAL = "#5F8D8B"
    SOFT_ROSE = "#A87C7C"


USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
SKILL_NAME_MAX_LENGTH = 124

PROJECTS_PER_PAGE = 12
PARTICIPANTS_PER_PAGE = 12
SKILL_AUTOCOMPLETE_LIMIT = 10

DEFAULT_POSTGRES_PORT = 5436

PHONE_LOCAL_LENGTH = 11
PHONE_DIGITS_AFTER_PREFIX = 10

AVATAR_IMAGE_SIZE = 256
AVATAR_FONT_SIZE = 120
AVATAR_TEXT_Y_OFFSET = 10
AVATAR_FONT_NAME = "DejaVuSans-Bold.ttf"
AVATAR_LETTER_LENGTH = 1
AVATAR_TEXT_ANCHOR = (0, 0)
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_BACKGROUND_COLORS = tuple(color.value for color in AvatarBackgroundColor)

ADMIN_AVATAR_SIZE = 48

GITHUB_HOSTS = frozenset({"github.com", "www.github.com"})

RUSSIAN_PLURAL_BASE = 10
RUSSIAN_PLURAL_HUNDRED_BASE = 100
RUSSIAN_PLURAL_TEENS_START = 11
RUSSIAN_PLURAL_TEENS_END = 14
RUSSIAN_PLURAL_ONE_ENDING = 1
RUSSIAN_PLURAL_FEW_START = 2
RUSSIAN_PLURAL_FEW_END = 4
